version: "3.9"

services:
  postgresql:
    container_name: postgres_container
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DATABASE: quarkus-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_ALLOW_EMPTY_PASSWORD: 1
    
    ports:
      - "3306:5432"
    networks:
      - docker-net

    volumes:
      # create default tables
      - ./tables/create_postgres_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      # backup# sql data
      # - ./mysql:/var/lib/mysql

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres123
    ports:
      - "5050:80"
    networks:
      - docker-net

# allows docker services to communicate
networks:
  docker-net:
    driver: bridge
